# Github Action to generate a contribution graph with a snake eating contributions.

name: Generate Contributions Snake

# Controls when the workflow will run
on:
  schedule:
    # Runs at 12am and 12pm
    - cron: "0 0,12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every push on the master branch
  push:
    branches:
    - main

# Sequence of runs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: update snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
